export const migrationTableSpecs = Object.freeze([
  {
    source: 'bp3_plot_owners',
    target: 'bp4_plot_owners',
    primaryKey: ['plot_id'],
    required: true,
  },
  {
    source: 'bp3_voice_channels',
    target: 'bp4_voice_channels',
    primaryKey: ['id'],
    required: true,
  },
  {
    source: 'bp3_voice_participants',
    target: 'bp4_voice_participants',
    primaryKey: ['channel_id', 'user_id'],
    required: true,
  },
  {
    source: 'bp3_home_access_rules',
    target: 'bp4_home_access_rules',
    primaryKey: ['plot_id'],
    required: true,
  },
  {
    source: 'bp3_home_visitors',
    target: 'bp4_home_visitors',
    primaryKey: ['plot_id', 'user_id'],
    required: true,
  },
  {
    source: 'bp3_home_access_requests',
    target: 'bp4_home_access_requests',
    primaryKey: ['id'],
    required: true,
  },
  {
    source: 'bp3_home_access_grants',
    target: 'bp4_home_access_grants',
    primaryKey: ['id'],
    required: true,
  },
  {
    source: 'bp3_home_visit_logs',
    target: 'bp4_home_visit_logs',
    primaryKey: ['id'],
    required: true,
  },
  {
    source: 'bp3_p1_item_catalog',
    target: 'bp4_item_catalog',
    primaryKey: ['item_id'],
    required: false,
  },
  {
    source: 'bp3_p1_world_events',
    target: 'bp4_world_events',
    primaryKey: ['id'],
    required: false,
  },
  {
    source: 'bp3_p1_tasks',
    target: 'bp4_tasks',
    primaryKey: ['id'],
    required: false,
  },
  {
    source: 'bp3_p1_task_instances',
    target: 'bp4_task_instances',
    primaryKey: ['id'],
    required: false,
  },
  {
    source: 'bp3_p1_resource_nodes',
    target: 'bp4_resource_nodes',
    primaryKey: ['id'],
    required: false,
  },
  {
    source: 'bp3_p1_inventories',
    target: 'bp4_inventories',
    primaryKey: ['user_id'],
    required: false,
  },
  {
    source: 'bp3_p1_inventory_items',
    target: 'bp4_inventory_items',
    primaryKey: ['user_id', 'item_id'],
    required: false,
  },
  {
    source: 'bp3_p1_inventory_transactions',
    target: 'bp4_inventory_transactions',
    primaryKey: ['id'],
    required: false,
  },
  {
    source: 'bp3_p1_reward_grants',
    target: 'bp4_reward_grants',
    primaryKey: ['id'],
    required: false,
  },
  {
    source: 'bp3_p2_avatar_states',
    target: 'bp4_avatar_states',
    primaryKey: ['user_id'],
    required: false,
  },
  {
    source: 'bp3_p2_home_messages',
    target: 'bp4_home_messages',
    primaryKey: ['id'],
    required: false,
  },
]);
